server:
  port: 8081
spring:
  profiles:
    active: peer1
  application:
    name: eureka-server

eureka:
  instance:
    hostname: peer1
  client:
    service-url:
      defaultZone: http://peer2:8082/eureka/
