server:
  port: 81
spring:
  application:
    name: order-server
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-gw0l3r8gekk6dhd4beo.mysql.cn-chengdu.rds.aliyuncs.com:3306/water_order?serverTimezone=GMT%2B8&useSSL=true
    username: user3
    password: Student@
  cloud:
    nacos:
      discovery:
        server-addr: localhost:80
        cluster-name: KM
        namespace: feeae11e-87c6-4509-8e77-68dc3ba1bb61
        # 要调用的微服务必须在同一个命名空间
  rabbitmq:
    host: 47.95.6.191
    port: 5672 # 端口
    virtual-host: / # 虚拟主机
    username: admin # 用户名
    password: 194911 # 密码
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 1 # 每次只能获取一条消息，处理完成才能获取下一个消息;用于WorkQueue模型
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
  redis:
    host: 127.0.0.1
    port: 6379

#eureka:
#  client:
#    service-url:
#      defaultZone: http://peer1:8081/eureka,http://peer2:8082/eureka/
##      defaultZone: http://127.0.0.1:10086/eureka


ribbon:
  eager-load:
    enabled: true # 开启饥饿加载
    clients: # 指定饥饿加载的服务名称
      - user-server

feign:
  client:
    config:
      default: # default全局的配置
        loggerLevel: BASIC # 日志级别，BASIC就是基本的请求和响应信息
  httpclient:
    enabled: true # 开启feign对HttpClient的支持
    max-connections: 200 # 最大的连接数
    max-connections-per-route: 50 # 每个路径的最大连接数
  hystrix:
    enabled: true

mybatis-plus:
  global-config:
    db-config:
      id-type: auto

springdoc:
  swagger-ui:
    path: /swagger-ui

redisson:
  address: redis://127.0.0.1:6379

order:
  ratelimit:
    create:
      rate: 40
      interval: 1
    accept:
      rate: 20
      interval: 1
  product:
    bloom-refresh-cron: "0 15 * * * ?"

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 10000
  threadpool:
    default:
      coreSize: 20
      maxQueueSize: 200

